language: ruby
bundler_args: --without development
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq wbritish
  - cp config/database.travis.yml config/database.yml
  - export TZ=Europe/London
before_script:
  - bundle exec rake db:create
  - bundle exec rake db:schema:load
  - mysql -e "CREATE DATABASE efg_test1;"
  - mysql -e "CREATE DATABASE efg_test2;"
  - mysql -e "CREATE DATABASE efg_test3;"
  - mysql -e "CREATE DATABASE efg_test4;"
  - mysql -e "CREATE DATABASE efg_test5;"
  - mysql -e "CREATE DATABASE efg_test6;"
  - mysql -e "CREATE DATABASE efg_test7;"
  - mysql -e "CREATE DATABASE efg_test8;"
cache: bundler
script:
  - PARALLEL_TEST_PROCESSORS=8 bundle exec rake
rvm:
  - 2.1.4
branches:
  except:
    - master
    - release
notifications:
  email: false
