require "rails_helper"

describe "Loan summary" do
  it "disables 'View Premium Schedule' link for CfeUsers when schedule
      has not yet been generated by the lender" do
    cfe_user = FactoryGirl.create(:cfe_user)
    loan_without_premium_schedule = FactoryGirl.create(:loan, :completed)

    login_as(cfe_user, scope: :user)
    visit loan_path(loan_without_premium_schedule)

    expect(disabled_premium_schedule_button).to be_present
  end

  def disabled_premium_schedule_button
    find(".btn.disabled", text: "View Premium Schedule")
  end
end
